# Generated by Django 4.1 on 2022-11-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltimetable',
            name='lesson_date',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Субота'), (6, 'Воскресенье')]),
        ),
    ]
