# Generated by Django 4.1 on 2022-08-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='learned_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.schoolclass'),
        ),
    ]
