# Generated by Django 4.1 on 2022-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_evaluation_options_homeworkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='student_class',
            field=models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый'), (6, 'Шестой'), (7, 'Седьмой'), (8, 'Восьмой'), (9, 'Девятый'), (10, 'Десятый'), (11, 'Одиннадцатый')]),
        ),
    ]
