# Generated by Django 4.1 on 2022-11-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_schooltimetable_lesson_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookwithclass',
            old_name='book',
            new_name='time_table',
        ),
    ]
