# Generated by Django 4.1 on 2022-08-31 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_schoolclass_number_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['number_class', 'name_class']},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=60, message='Максимум 60'), django.core.validators.MinValueValidator(limit_value=5, message='Минимум 5')], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик')], max_length=30, verbose_name='Я'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='learned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.schoolclass', verbose_name='Выбор класса'),
        ),
        migrations.CreateModel(
            name='BookWithClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.books')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.schoolclass')),
            ],
        ),
    ]
