# Generated by Django 4.1 on 2022-08-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_homeworkmodel_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmodel',
            name='date_create_homework',
            field=models.DateField(null=True),
        ),
    ]
