# Generated by Django 4.1 on 2022-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_homeworkmodel_date_create_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmodel',
            name='date_end_of_homrwork',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='date_create_homework',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
