# Generated by Django 4.1 on 2022-08-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_homeworkmodel_date_end_of_homrwork_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkmodel',
            name='date_create_homework',
        ),
    ]
