# Generated by Django 4.1 on 2022-11-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_bookwithclass_time_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='schooltimetable',
            name='lesson_date',
        ),
        migrations.AddField(
            model_name='schooltimetable',
            name='lesson_date',
            field=models.ManyToManyField(to='diary.dayofweak'),
        ),
    ]
