# Generated by Django 4.1 on 2022-08-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_remove_homeworkmodel_date_create_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkmodel',
            old_name='date_end_of_homrwork',
            new_name='date_end_of_homework',
        ),
    ]
