# Generated by Django 4.1 on 2022-10-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='articles_images/%Y/%m/%d')),
                ('date_create', models.DateTimeField()),
                ('date_edit', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
